spring:
  application:
    name: SpringWebApp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: db
    password: 159753

jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  defer-datasource-initialization: true

flyway:
  url: jdbc:postgresql://localhost:5432/db
  user: postgres
  password: 159753
  enabled: true
  locations:
    - 'classpath:db/migration'